// PU Stone Panels — 产品数据集中管理
// 数据来源：PU文化石外贸公司报价单（2024-08-19）+ 高仿真PU文化石画册
// 所有价格、型号、尺寸、MOQ均来自真实报价单，禁止虚构

export interface PUStoneProduct {
  id: string;
  code: string;
  name: string;
  series: string;
  seriesSlug: string;
  size: string;
  thickness: string;
  color: string;
  moq: number;
  unit: string;
  unitPrice: number | null;
  currency: string;
  incoterm: string;
  packaging: string;
  pcsPerCarton: number;
  cartonSize: string;
  netWeightPerCarton: string;
  weightPerPiece: string;
  leadTime: string;
  remarks: string;
  image: string;
  // 多图类型支持 — 按产品型号绑定，找不到时前端显示占位
  textureImage?: string;
  applicationImage?: string;
}

export interface PUStoneSeries {
  slug: string;
  name: string;
  nameZh: string;
  description: string;
}

export const puStoneSeries: PUStoneSeries[] = [
  {
    slug: "stone-skin",
    name: "Stone Skin Series",
    nameZh: "石皮系列",
    description: "Thin-profile PU stone skin panels with film coating and paint finish for seamless wall coverage.",
  },
  {
    slug: "mushroom-stone",
    name: "Mushroom Stone Series",
    nameZh: "蘑菇石系列",
    description: "3D mushroom-textured PU stone panels with pronounced relief and ridge detailing.",
  },
  {
    slug: "rock-stone",
    name: "Rock Stone Series",
    nameZh: "山岩石系列",
    description: "Mountain rock, flowing stone, feather stone and moon stone textures replicating natural rock formations.",
  },
  {
    slug: "9-block",
    name: "9 Block Component Series",
    nameZh: "九宫格系列",
    description: "Modular nine-grid pattern panels creating geometric interlocking designs.",
  },
  {
    slug: "culture-brick",
    name: "Culture Brick Series",
    nameZh: "文化砖系列",
    description: "Brick and tile pattern PU panels replicating traditional masonry and exterior wall brickwork.",
  },
  {
    slug: "geometry",
    name: "Geometry Series",
    nameZh: "几何系列",
    description: "Geometric pattern panels including pyramid, clock, bread stone, water cube and wire-brushed designs.",
  },
  {
    slug: "large-board",
    name: "Large Board Series",
    nameZh: "大板系列",
    description: "Extra-large format PU stone boards up to 2900mm for continuous seamless feature walls.",
  },
  {
    slug: "color-series",
    name: "Color Series",
    nameZh: "色彩系列",
    description: "Multi-color and mixed-tone PU stone panels with premium color finishes.",
  },
  {
    slug: "in-mold-paint",
    name: "In-Mold Paint Series",
    nameZh: "模内漆系列",
    description: "In-mold painted PU panels with integrated color for superior durability and large-format options.",
  },
];

const IMG_BASE = "/images/products/pu-stone";
const LEAD_TIME = "Please contact our sales team for confirmation.";
const CURRENCY = "CNY";
const INCOTERM = "EXW";

export const puStoneProducts: PUStoneProduct[] = [
  // ===== Stone Skin Series =====
  {
    id: "pu-jcg",
    code: "JCG",
    name: "Stone Skin 16MM (Film Coating & Paint)",
    series: "Stone Skin Series",
    seriesSlug: "stone-skin",
    size: "1200*600",
    thickness: "16mm",
    color: "Multiple colors available",
    moq: 16,
    unit: "pcs",
    unitPrice: 28,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "16 pcs/ctn",
    pcsPerCarton: 16,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.1kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCG.jpg`,
    textureImage: `${IMG_BASE}/JCG-A.jpg`,
    applicationImage: `${IMG_BASE}/JCG-B.jpg`,
  },
  {
    id: "pu-jca",
    code: "JCA",
    name: "Stone Skin 30MM (Film Coating & Paint) with ridge",
    series: "Stone Skin Series",
    seriesSlug: "stone-skin",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 9,
    unit: "pcs",
    unitPrice: 31,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "12.6kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCA.jpg`,
  },
  {
    id: "pu-jca-1",
    code: "JCA-1",
    name: "Pitted Stone Skin",
    series: "Stone Skin Series",
    seriesSlug: "stone-skin",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 9,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "12.6kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCA-1.jpg`,
  },

  // ===== Mushroom Stone Series =====
  {
    id: "pu-jcb",
    code: "JCB",
    name: "Mushroom Stone 50MM (Film Coating & Paint) with ridge",
    series: "Mushroom Stone Series",
    seriesSlug: "mushroom-stone",
    size: "1200*600",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 36,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn (with ridge) / 10 pcs/ctn (without ridge)",
    pcsPerCarton: 6,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "10.2kg",
    weightPerPiece: "1.6kg (with ridge) / 1.4kg (without ridge)",
    leadTime: LEAD_TIME,
    remarks: "With ridge (带背筋) ¥36/pcs; Without ridge (无筋) ¥33/pcs. Packing: 6 pcs/ctn (ridged) or 10 pcs/ctn (ridgeless).",
    image: `${IMG_BASE}/JCB.jpg`,
  },

  // ===== Rock Stone Series =====
  {
    id: "pu-jcc001",
    code: "JCC001",
    name: "Mountain Rock Stone 60MM (Film Coating & Paint) with ridge",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "60mm",
    color: "Multiple colors available",
    moq: 5,
    unit: "pcs",
    unitPrice: 45,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "9.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCC001.jpg`,
  },
  {
    id: "pu-jcc003",
    code: "JCC003",
    name: "Mountain Rock Stone 60MM (Film Coating & Paint) with ridge",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "60mm",
    color: "Multiple colors available",
    moq: 5,
    unit: "pcs",
    unitPrice: 45,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "9.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊). Different texture pattern from JCC001.",
    image: `${IMG_BASE}/JCC003.jpg`,
  },
  {
    id: "pu-jcc004",
    code: "JCC004",
    name: "Mountain Rock Stone 35MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "35mm",
    color: "Multiple colors available",
    moq: 9,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "13.1kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCC004.jpg`,
  },
  {
    id: "pu-jcc005",
    code: "JCC005",
    name: "River Rock Stone 30MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 9,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "13.1kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCC005.jpg`,
  },
  {
    id: "pu-jcc006",
    code: "JCC006",
    name: "Small Turtle Pattern Stone 25MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "25mm",
    color: "Single color",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Single color ¥38/pcs. Multi-color version see JCC006-1 (¥50/pcs).",
    image: `${IMG_BASE}/JCC006.jpg`,
  },
  {
    id: "pu-jcc006-1",
    code: "JCC006-1",
    name: "Small Turtle Pattern Stone 25MM — Multi-Color",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "25mm",
    color: "Multi-color",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version of JCC006.",
    image: `${IMG_BASE}/JCC006-1.jpg`,
  },
  {
    id: "pu-jcc007",
    code: "JCC007",
    name: "Castle Stone 30MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "30mm",
    color: "Single color",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCC007-1.",
    image: `${IMG_BASE}/JCC007.jpg`,
  },
  {
    id: "pu-jcc009",
    code: "JCC009",
    name: "Fine Strip Stone 30MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCC009.jpg`,
  },
  {
    id: "pu-jcf002",
    code: "JCF002",
    name: "Flowing Stone 25MM (Film Coating & Paint) with ridge",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCF002.jpg`,
  },
  {
    id: "pu-jcf001",
    code: "JCF001",
    name: "Feather Stone 50MM (Film Coating & Paint) with ridge",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "900*200",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 30,
    unit: "pcs",
    unitPrice: 16,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "30 pcs/ctn",
    pcsPerCarton: 30,
    cartonSize: "920x420x360mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊). Smaller format: 900x200mm.",
    image: `${IMG_BASE}/JCF001.jpg`,
  },
  {
    id: "pu-jcf003",
    code: "JCF003",
    name: "Moon Stone 30MM (Film Coating & Paint) with ridge",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "40mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 40,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15.3kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCF003.jpg`,
  },
  {
    id: "pu-jcc008",
    code: "JCC008",
    name: "Crushed Stone 30MM (Film Coating & Paint)",
    series: "Rock Stone Series",
    seriesSlug: "rock-stone",
    size: "1200*600",
    thickness: "30mm",
    color: "Single color",
    moq: 8,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15.2kg",
    weightPerPiece: "1.9kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCC008-1 (¥60/pcs).",
    image: `${IMG_BASE}/JCC008.jpg`,
  },

  // ===== 9 Block Component Series =====
  {
    id: "pu-jcd",
    code: "JCD",
    name: "9 Block Component 30MM (Film Coating & Paint)",
    series: "9 Block Component Series",
    seriesSlug: "9-block",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15.3kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCD.jpg`,
  },
  {
    id: "pu-jcd006",
    code: "JCD006",
    name: "Triumph Arch 30MM (Film Coating & Paint)",
    series: "9 Block Component Series",
    seriesSlug: "9-block",
    size: "1200*600",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 55,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15.3kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCD006.jpg`,
  },
  {
    id: "pu-jcd007",
    code: "JCD007",
    name: "9 Block Double-Sided Flower 60MM (Film Coating & Paint)",
    series: "9 Block Component Series",
    seriesSlug: "9-block",
    size: "1200*600",
    thickness: "60mm",
    color: "Multiple colors available",
    moq: 5,
    unit: "pcs",
    unitPrice: 100,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.3kg",
    weightPerPiece: "3.5kg",
    leadTime: LEAD_TIME,
    remarks: "Double-sided pattern. Heavier panel.",
    image: `${IMG_BASE}/JCD007.jpg`,
  },

  // ===== Culture Brick Series =====
  {
    id: "pu-jch001",
    code: "JCH001",
    name: "Blue Brick 30MM (Film Coating & Paint)",
    series: "Culture Brick Series",
    seriesSlug: "culture-brick",
    size: "1200*600",
    thickness: "30mm",
    color: "Single color",
    moq: 10,
    unit: "pcs",
    unitPrice: 40,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "10 pcs/ctn",
    pcsPerCarton: 10,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "19.2kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCH001-1 (¥50/pcs).",
    image: `${IMG_BASE}/JCH001.jpg`,
  },
  {
    id: "pu-jch002",
    code: "JCH002",
    name: "Culture Brick 25MM (Film Coating & Paint)",
    series: "Culture Brick Series",
    seriesSlug: "culture-brick",
    size: "1200*600",
    thickness: "25mm",
    color: "Single color",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCH002-1 (¥50/pcs).",
    image: `${IMG_BASE}/JCH002.jpg`,
  },
  {
    id: "pu-jch004",
    code: "JCH004",
    name: "Strip Stone 25MM (Film Coating & Paint)",
    series: "Culture Brick Series",
    seriesSlug: "culture-brick",
    size: "1200*600",
    thickness: "25mm",
    color: "Single color",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCH004-1 (¥50/pcs).",
    image: `${IMG_BASE}/JCH004.jpg`,
  },
  {
    id: "pu-jch005",
    code: "JCH005",
    name: "Exterior Wall Brick 3CM (Film Coating & Paint)",
    series: "Culture Brick Series",
    seriesSlug: "culture-brick",
    size: "1500*750",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 58,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1530x770x320mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1500x750mm.",
    image: `${IMG_BASE}/JCH005.jpg`,
  },
  {
    id: "pu-jch006",
    code: "JCH006",
    name: "Exterior Wall Brick 5CM (Film Coating & Paint)",
    series: "Culture Brick Series",
    seriesSlug: "culture-brick",
    size: "1500*750",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1530x770x320mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.8kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1500x750mm. Thicker profile.",
    image: `${IMG_BASE}/JCH006.jpg`,
  },

  // ===== Geometry Series =====
  {
    id: "pu-jce001",
    code: "JCE001",
    name: "Clock Stone 25MM (Film Coating & Paint) with ridge",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCE001.jpg`,
  },
  {
    id: "pu-jce002",
    code: "JCE002",
    name: "Pyramid Stone 25MM (Film Coating & Paint) with ridge",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 15,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "15 pcs/ctn",
    pcsPerCarton: 15,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCE002.jpg`,
  },
  {
    id: "pu-jce003",
    code: "JCE003",
    name: "Bread Stone 25MM (Film Coating & Paint) with ridge",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "19.2kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCE003.jpg`,
  },
  {
    id: "pu-jce004",
    code: "JCE004",
    name: "Future Stone 25MM (Film Coating & Paint) with ridge",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCE004.jpg`,
  },
  {
    id: "pu-jce005",
    code: "JCE005",
    name: "Cement Board 25MM (Film Coating & Paint) with ridge",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 10,
    unit: "pcs",
    unitPrice: 52,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "10 pcs/ctn",
    pcsPerCarton: 10,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "With ridge (有背脊)",
    image: `${IMG_BASE}/JCE005.jpg`,
  },
  {
    id: "pu-jce006",
    code: "JCE006",
    name: "Wave Board 20MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "20mm",
    color: "Single color / Multi-color",
    moq: 14,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "14 pcs/ctn",
    pcsPerCarton: 14,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15kg",
    weightPerPiece: "1.2kg",
    leadTime: LEAD_TIME,
    remarks: "Single color ¥38/pcs; Multi-color ¥50/pcs.",
    image: `${IMG_BASE}/JCE006.jpg`,
  },
  {
    id: "pu-jcj001",
    code: "JCJ001",
    name: "Diamond Wire-Brushed 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 40,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "19.2kg",
    weightPerPiece: "1.6kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ001.jpg`,
  },
  {
    id: "pu-jcj002",
    code: "JCJ002",
    name: "Swirl Geometry Wire-Brushed 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 16,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "16 pcs/ctn",
    pcsPerCarton: 16,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "24kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ002.jpg`,
  },
  {
    id: "pu-jcj003",
    code: "JCJ003",
    name: "Water Cube 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Single color",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version see JCJ003-1 / JCJ003-2 (¥50/pcs).",
    image: `${IMG_BASE}/JCJ003.jpg`,
    textureImage: `${IMG_BASE}/JCJ003-A.jpg`,
    applicationImage: `${IMG_BASE}/JCJ003-B.jpg`,
  },
  {
    id: "pu-jcj004",
    code: "JCJ004",
    name: "Geometry 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ004.jpg`,
  },
  {
    id: "pu-jcj005",
    code: "JCJ005",
    name: "Flower Pattern 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 14,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "14 pcs/ctn",
    pcsPerCarton: 14,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ005.jpg`,
  },
  {
    id: "pu-jcj006",
    code: "JCJ006",
    name: "Travertine Geometry 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ006.jpg`,
  },
  {
    id: "pu-jcj007",
    code: "JCJ007",
    name: "3D Space 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCJ007.jpg`,
  },
  {
    id: "pu-jcj008",
    code: "JCJ008",
    name: "Euryops Panel A/B 25MM (Film Coating & Paint)",
    series: "Geometry Series",
    seriesSlug: "geometry",
    size: "1200*600",
    thickness: "25mm",
    color: "Multiple colors available",
    moq: 12,
    unit: "pcs",
    unitPrice: 38,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "18kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Available in A and B variants.",
    image: `${IMG_BASE}/JCJ008.jpg`,
    textureImage: `${IMG_BASE}/JCJ008-A.jpg`,
    applicationImage: `${IMG_BASE}/JCJ008-B.jpg`,
  },

  // ===== Large Board Series =====
  {
    id: "pu-jck003",
    code: "JCK003",
    name: "Carbonized Wood (Customizable Aged Effect)",
    series: "Large Board Series",
    seriesSlug: "large-board",
    size: "2400*600",
    thickness: "20mm",
    color: "Multiple colors available",
    moq: 15,
    unit: "pcs",
    unitPrice: 130,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "15 pcs/ctn",
    pcsPerCarton: 15,
    cartonSize: "2420x620x200mm",
    netWeightPerCarton: "32kg",
    weightPerPiece: "4kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 2400x600mm. Customizable aged/antique effect available.",
    image: `${IMG_BASE}/JCK003.jpg`,
  },
  {
    id: "pu-jck004",
    code: "JCK004",
    name: "Continuous Crushed Stone 20-100MM (Film Coating & Paint)",
    series: "Large Board Series",
    seriesSlug: "large-board",
    size: "2400*600",
    thickness: "20-80mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 145,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn",
    pcsPerCarton: 6,
    cartonSize: "2420x620x320mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 2400x600mm. Variable thickness 20-80mm for continuous pattern.",
    image: `${IMG_BASE}/JCK004.jpg`,
  },
  {
    id: "pu-jck005",
    code: "JCK005",
    name: "Continuous Mountain Rock 20-100MM (Film Coating & Paint)",
    series: "Large Board Series",
    seriesSlug: "large-board",
    size: "2900*600",
    thickness: "20-70mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 150,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn",
    pcsPerCarton: 6,
    cartonSize: "2920x620x320mm",
    netWeightPerCarton: "42kg",
    weightPerPiece: "7kg",
    leadTime: LEAD_TIME,
    remarks: "Extra-large format: 2900x600mm. Variable thickness 20-70mm for continuous pattern.",
    image: `${IMG_BASE}/JCK005.jpg`,
  },

  // ===== Color Series =====
  {
    id: "pu-jcc007-1",
    code: "JCC007-1",
    name: "Color Castle Stone 30MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "30mm",
    color: "Multi-color",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "16.8kg",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version of JCC007.",
    image: `${IMG_BASE}/JCC007-1.jpg`,
  },
  {
    id: "pu-jcc008-1",
    code: "JCC008-1",
    name: "Color Crushed Stone 30MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "30mm",
    color: "Multi-color",
    moq: 8,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "15.2kg",
    weightPerPiece: "1.9kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color version of JCC008.",
    image: `${IMG_BASE}/JCC008-1.jpg`,
  },
  {
    id: "pu-jcc004-1",
    code: "JCC004-1",
    name: "Two-Tone Mountain Rock 35MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "35mm",
    color: "Two-tone",
    moq: 9,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "13.1kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Two-tone version of JCC004.",
    image: `${IMG_BASE}/JCC004-1.jpg`,
  },
  {
    id: "pu-jcc001-1",
    code: "JCC001-1",
    name: "Snow Peak Mountain Rock 60MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "60mm",
    color: "Snow peak",
    moq: 5,
    unit: "pcs",
    unitPrice: 58,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "9.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "Color version of JCC001.",
    image: `${IMG_BASE}/JCC001-1.jpg`,
  },
  {
    id: "pu-jcc001-2",
    code: "JCC001-2",
    name: "Yellow Dragon Jade Mountain Rock 60MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "60mm",
    color: "Yellow dragon jade",
    moq: 5,
    unit: "pcs",
    unitPrice: 58,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "9.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "Color version of JCC001.",
    image: `${IMG_BASE}/JCC001-2.jpg`,
  },
  {
    id: "pu-jcc005-1",
    code: "JCC005-1",
    name: "Color River Rock Stone 30MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "30mm",
    color: "Multi-color",
    moq: 9,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "9 pcs/ctn",
    pcsPerCarton: 9,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "13.1kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Color version of JCC005.",
    image: `${IMG_BASE}/JCC005-1.jpg`,
  },
  {
    id: "pu-jch001-1",
    code: "JCH001-1",
    name: "Retro Brick 25MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "25mm",
    color: "Retro",
    moq: 10,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "10 pcs/ctn",
    pcsPerCarton: 10,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "19.2kg",
    weightPerPiece: "1.6kg",
    leadTime: LEAD_TIME,
    remarks: "Retro color version of JCH001.",
    image: `${IMG_BASE}/JCH001-1.jpg`,
    textureImage: `${IMG_BASE}/JCH001-1-A.jpg`,
    applicationImage: `${IMG_BASE}/JCH001-1-B.jpg`,
  },
  {
    id: "pu-jch002-1",
    code: "JCH002-1",
    name: "Two-Tone Culture Brick 25MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "25mm",
    color: "Two-tone",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Two-tone version of JCH002.",
    image: `${IMG_BASE}/JCH002-1.jpg`,
  },
  {
    id: "pu-jch004-1",
    code: "JCH004-1",
    name: "Color Strip Stone 25MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "25mm",
    color: "Multi-color",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "21kg",
    weightPerPiece: "1.6kg",
    leadTime: LEAD_TIME,
    remarks: "Color version of JCH004.",
    image: `${IMG_BASE}/JCH004-1.jpg`,
  },
  {
    id: "pu-jcj003-1",
    code: "JCJ003-1",
    name: "Color Water Cube 25MM (Variant 1)",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "25mm",
    color: "Multi-color",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "20kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Color variant 1 of JCJ003.",
    image: `${IMG_BASE}/JCJ003-1.jpg`,
  },
  {
    id: "pu-jcj003-2",
    code: "JCJ003-2",
    name: "Color Water Cube 25MM (Variant 2)",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "25mm",
    color: "Multi-color",
    moq: 12,
    unit: "pcs",
    unitPrice: 50,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "12 pcs/ctn",
    pcsPerCarton: 12,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "20kg",
    weightPerPiece: "1.5kg",
    leadTime: LEAD_TIME,
    remarks: "Color variant 2 of JCJ003.",
    image: `${IMG_BASE}/JCJ003-2.jpg`,
  },
  {
    id: "pu-jcl001-1",
    code: "JCL001-1",
    name: "Color Disordered Stone 40MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1250*560",
    thickness: "40mm",
    color: "Multi-color",
    moq: 8,
    unit: "pcs",
    unitPrice: 75,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1230x620x280mm",
    netWeightPerCarton: "16kg",
    weightPerPiece: "1.6kg",
    leadTime: LEAD_TIME,
    remarks: "Non-standard size: 1250x560mm.",
    image: `${IMG_BASE}/JCL001-1.jpg`,
  },
  {
    id: "pu-jcn007",
    code: "JCN007",
    name: "Large Block Stone 50MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 5,
    unit: "pcs",
    unitPrice: 75,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "8.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCN007.jpg`,
  },
  {
    id: "pu-jcn008",
    code: "JCN008",
    name: "Small Pebble Stone 50MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 75,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn",
    pcsPerCarton: 6,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "8.5kg",
    weightPerPiece: "1.7kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCN008.jpg`,
  },
  {
    id: "pu-jcn006",
    code: "JCN006",
    name: "Rock Stone 40MM",
    series: "Color Series",
    seriesSlug: "color-series",
    size: "1200*600",
    thickness: "40mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1220x620x300mm",
    netWeightPerCarton: "12.8kg",
    weightPerPiece: "1.6kg",
    leadTime: LEAD_TIME,
    remarks: "",
    image: `${IMG_BASE}/JCN006.jpg`,
  },

  // ===== In-Mold Paint Series =====
  {
    id: "pu-jcm001",
    code: "JCM001",
    name: "In-Mold Culture Brick 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1220*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1220x300mm.",
    image: `${IMG_BASE}/JCM001.jpg`,
  },
  {
    id: "pu-jcm002",
    code: "JCM002",
    name: "In-Mold Sea Decaying Wood 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1160*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1160x300mm.",
    image: `${IMG_BASE}/JCM002.jpg`,
  },
  {
    id: "pu-jcm003",
    code: "JCM003",
    name: "In-Mold Tree Ring Wood 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1200*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1200x300mm.",
    image: `${IMG_BASE}/JCM003.jpg`,
  },
  {
    id: "pu-jcm004",
    code: "JCM004",
    name: "In-Mold Rock Stone Type A 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1160*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn",
    pcsPerCarton: 6,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1160x300mm.",
    image: `${IMG_BASE}/JCM004.jpg`,
  },
  {
    id: "pu-jcm005",
    code: "JCM005",
    name: "In-Mold Castle Stone 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1200*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1200x300mm.",
    image: `${IMG_BASE}/JCM005.jpg`,
  },
  {
    id: "pu-jcm006",
    code: "JCM006",
    name: "In-Mold Small Rock 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1200*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1200x300mm.",
    image: `${IMG_BASE}/JCM006.jpg`,
  },
  {
    id: "pu-jcm007",
    code: "JCM007",
    name: "In-Mold Rock Stone Type B 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1160*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1160x300mm.",
    image: `${IMG_BASE}/JCM007.jpg`,
  },
  {
    id: "pu-jcm008",
    code: "JCM008",
    name: "In-Mold Wood Board 30MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1200*300",
    thickness: "30mm",
    color: "Multiple colors available",
    moq: 8,
    unit: "pcs",
    unitPrice: 60,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "8 pcs/ctn",
    pcsPerCarton: 8,
    cartonSize: "1240x350x240mm",
    netWeightPerCarton: "",
    weightPerPiece: "1.4kg",
    leadTime: LEAD_TIME,
    remarks: "In-mold paint. Size: 1200x300mm.",
    image: `${IMG_BASE}/JCM008.jpg`,
  },
  {
    id: "pu-jcn001",
    code: "JCN001",
    name: "Broken Mountain Stone 50MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1500*750",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 175,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1540x780x380mm",
    netWeightPerCarton: "",
    weightPerPiece: "3.5kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1500x750mm.",
    image: `${IMG_BASE}/JCN001.jpg`,
  },
  {
    id: "pu-jcn002",
    code: "JCN002",
    name: "Sea Reef Rock 50MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1500*750",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 175,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1540x780x380mm",
    netWeightPerCarton: "",
    weightPerPiece: "3.5kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1500x750mm.",
    image: `${IMG_BASE}/JCN002.jpg`,
  },
  {
    id: "pu-jcn003",
    code: "JCN003",
    name: "Castle Stone 50MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1500*750",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 7,
    unit: "pcs",
    unitPrice: 175,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "7 pcs/ctn",
    pcsPerCarton: 7,
    cartonSize: "1540x780x380mm",
    netWeightPerCarton: "",
    weightPerPiece: "3.5kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1500x750mm.",
    image: `${IMG_BASE}/JCN003.jpg`,
  },
  {
    id: "pu-jcn004",
    code: "JCN004",
    name: "Pebble Stone 85MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1600*880",
    thickness: "85mm",
    color: "Multiple colors available",
    moq: 4,
    unit: "pcs",
    unitPrice: 380,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "4 pcs/ctn",
    pcsPerCarton: 4,
    cartonSize: "1610x900x360mm",
    netWeightPerCarton: "",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "Extra-large format: 1600x880mm. Thickest profile: 85mm.",
    image: `${IMG_BASE}/JCN004.jpg`,
  },
  {
    id: "pu-jcn005",
    code: "JCN005",
    name: "Turtle Pattern Stone 50MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1600*870",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 5,
    unit: "pcs",
    unitPrice: 195,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "5 pcs/ctn",
    pcsPerCarton: 5,
    cartonSize: "1610x880x280mm",
    netWeightPerCarton: "",
    weightPerPiece: "4kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1600x870mm.",
    image: `${IMG_BASE}/JCN005.jpg`,
  },
  {
    id: "pu-jcn007w",
    code: "JCN007-W",
    name: "White Sandstone 50MM",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "1189*841",
    thickness: "50mm",
    color: "Multiple colors available",
    moq: 6,
    unit: "pcs",
    unitPrice: 160,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "6 pcs/ctn",
    pcsPerCarton: 6,
    cartonSize: "1220x6860x330mm",
    netWeightPerCarton: "",
    weightPerPiece: "3.5kg",
    leadTime: LEAD_TIME,
    remarks: "Large format: 1189x841mm.",
    image: `${IMG_BASE}/JCN007-W.jpg`,
  },
  {
    id: "pu-jcn006b",
    code: "JCN006-B",
    name: "PU Beam Wood (per sqm)",
    series: "In-Mold Paint Series",
    seriesSlug: "in-mold-paint",
    size: "2550*150*100",
    thickness: "/",
    color: "Multiple colors available",
    moq: 2,
    unit: "sqm",
    unitPrice: 210,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "2 pcs/ctn",
    pcsPerCarton: 2,
    cartonSize: "2630x245x185mm",
    netWeightPerCarton: "",
    weightPerPiece: "",
    leadTime: LEAD_TIME,
    remarks: "Priced per square meter (¥210/sqm). Beam dimensions: 2550x150x100mm.",
    image: `${IMG_BASE}/JCN006-B.jpg`,
  },
];

// FAQ 数据 — 仅使用报价单和画册中确认的信息
export const puStoneFAQs = [
  {
    question: "What is the MOQ (Minimum Order Quantity) for PU stone panels?",
    answer:
      "MOQ varies by product model and is based on the minimum carton quantity. Most standard 1200x600mm panels have an MOQ of 5-16 pieces (one carton). Large-format panels (1500x750mm and above) have lower MOQs of 4-8 pieces. Please contact our sales team for the exact MOQ of your selected model.",
  },
  {
    question: "Can I order samples before placing a bulk order?",
    answer:
      "Yes. Please contact our sales team for confirmation. Sample availability and charges may vary by product.",
  },
  {
    question: "Are custom colors available?",
    answer:
      "Many models are available in both single-color and multi-color (色彩) versions. Multi-color versions are priced higher. Custom color matching is possible for project orders. Please contact our sales team for confirmation.",
  },
  {
    question: "What are the available trade terms (Incoterms)?",
    answer:
      "Our quoted prices are ex-factory (EXW) prices in CNY, tax-inclusive. FOB, CIF and other trade terms can be arranged upon request. Please contact our sales team for confirmation of shipping costs to your destination port.",
  },
  {
    question: "What is the lead time for production and delivery?",
    answer:
      "Please contact our sales team for confirmation. Lead time varies by product model, order quantity and production schedule.",
  },
  {
    question: "How are PU stone panels packaged for shipping?",
    answer:
      "Panels are packed in cartons with quantities ranging from 4 to 30 pieces per carton, depending on panel size and thickness. Carton dimensions are listed on each product detail page. 20GP and 40HQ container loading quantities are available upon request.",
  },
  {
    question: "Do you support project procurement and bulk orders?",
    answer:
      "Yes. We support project procurement with consolidated shipping. Please provide your project requirements, quantities and destination for a detailed quotation.",
  },
  {
    question: "How are shipping costs calculated?",
    answer:
      "Shipping costs depend on order volume, destination and shipping method (sea freight, air freight or land transport). We do not automatically calculate shipping. Please contact our sales team with your destination port for a freight quotation.",
  },
];

// 联系信息配置变量
export const PU_STONE_CONTACT = {
  email: "cindy@onestopbuildly.com",
  phone: "+86-13511316133",
  whatsapp: "+86-13511316133",
  company: "Haining Onestopbuildly Building Materials Co., Ltd.",
  address: "Room 108, Building 2, Fenghuang Commercial Building, Dingqiao Town, Haining, Zhejiang, China",
  factoryAddress: "No. 1, Shiquan Industrial Park, Tongyuan Town, Haiyan County, Jiaxing, Zhejiang",
};

// 工具函数
export function formatPrice(product: PUStoneProduct): string {
  if (product.unitPrice === null || product.unitPrice === undefined) {
    return "Price available on request";
  }
  return `${product.currency} ${product.unitPrice} / ${product.unit}`;
}

export function formatPriceShort(product: PUStoneProduct): string {
  if (product.unitPrice === null || product.unitPrice === undefined) {
    return "Request a Quote";
  }
  return `${product.currency} ${product.unitPrice}/${product.unit}`;
}

export function getProductsBySeries(seriesSlug: string): PUStoneProduct[] {
  return puStoneProducts.filter((p) => p.seriesSlug === seriesSlug);
}

export function getUniqueSizes(): string[] {
  return [...new Set(puStoneProducts.map((p) => p.size))].sort();
}

export function getUniqueSeries(): PUStoneSeries[] {
  return puStoneSeries;
}

export function getUniqueColors(): string[] {
  return [...new Set(puStoneProducts.map((p) => p.color))].sort();
}

export function getUniqueCodes(): string[] {
  return [...new Set(puStoneProducts.map((p) => p.code))].sort();
}
