// PVC Ceiling & Wall Panels — 产品数据集中管理
// 数据来源：Alibaba PVC天花板/墙板产品抓取数据（2024）
// 所有价格、型号、尺寸、MOQ均来自真实外贸报价，禁止虚构

export interface PVCPanelProduct {
  id: string;
  code: string;
  name: string;
  series: string;
  seriesSlug: string;
  size: string;
  thickness: string;
  color: string;
  moq: number;
  unit: string;
  unitPrice: number | null;
  currency: string;
  incoterm: string;
  packaging: string;
  pcsPerCarton: number;
  cartonSize: string;
  netWeightPerCarton: string;
  weightPerPiece: string;
  leadTime: string;
  remarks: string;
  image: string;
  // 多图类型支持 — 按产品型号绑定，找不到时前端显示占位
  textureImage?: string;
  applicationImage?: string;
}

export interface PVCPanelSeries {
  slug: string;
  name: string;
  nameZh: string;
  description: string;
}

export const pvcPanelSeries: PVCPanelSeries[] = [
  {
    slug: "uk-bathroom",
    name: "UK Bathroom Cladding Series",
    nameZh: "英国浴室板系列",
    description: "Waterproof 1m wide PVC shower wall panels for UK market, 10mm thickness, concrete grey, marble and granite finishes.",
  },
  {
    slug: "standard-ceiling",
    name: "Standard Ceiling 25cm Series",
    nameZh: "标准天花板25cm系列",
    description: "25cm width PVC ceiling panels with printing and lamination surface, 7-8mm thickness, 5.95m length.",
  },
  {
    slug: "wide-ceiling",
    name: "Wide Ceiling 30cm Series",
    nameZh: "宽幅天花板30cm系列",
    description: "30cm width fireproof heat-insulating and moisture-proof PVC ceiling panels for commercial and residential use.",
  },
  {
    slug: "glossy-printing",
    name: "Glossy Printing Series",
    nameZh: "高光印刷系列",
    description: "High-gloss surface PVC ceiling tiles with premium printing patterns for interior decoration.",
  },
  {
    slug: "laminated-wood",
    name: "Laminated Wood Grain Series",
    nameZh: "木纹覆膜系列",
    description: "Wood design laminated PVC panels with hot stamping technology and V-groove interlocking for seamless installation.",
  },
  {
    slug: "tongue-groove",
    name: "Tongue & Groove Series",
    nameZh: "锁扣系列",
    description: "V-groove tongue and groove interlocking PVC ceiling panels, 5.95m length for continuous coverage.",
  },
  {
    slug: "self-adhesive",
    name: "Self-Adhesive Series",
    nameZh: "自粘系列",
    description: "Peel & stick self-adhesive PVC wall panels with 3D geometric patterns for DIY installation.",
  },
  {
    slug: "hot-stamping",
    name: "Hot Stamping Series",
    nameZh: "烫印系列",
    description: "Decorative hot stamping PVC ceiling and wall panels with metallic finish for premium interiors.",
  },
];

const IMG_BASE = "/images/products/pvc-panel";
const LEAD_TIME = "Please contact our sales team for confirmation.";
const CURRENCY = "USD";
const INCOTERM = "FOB";

export const pvcPanelProducts: PVCPanelProduct[] = [
  // ===== UK Bathroom Cladding Series =====
  {
    id: "pvc-uk-bc001",
    code: "UK-BC001",
    name: "Moisture-Proof PVC Ceiling Panel Bathroom Wall Sheet",
    series: "UK Bathroom Cladding Series",
    seriesSlug: "uk-bathroom",
    size: "2400*1000*10mm",
    thickness: "10mm",
    color: "Concrete Grey",
    moq: 1000,
    unit: "sqm",
    unitPrice: 6,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "20 pcs/pallet",
    pcsPerCarton: 20,
    cartonSize: "2420*1020*150mm",
    netWeightPerCarton: "120kg",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "1m wide waterproof PVC shower wall panel designed for UK bathroom cladding market.",
    image: `${IMG_BASE}/UK-BC001.jpg`,
    textureImage: `${IMG_BASE}/UK-BC001-A.jpg`,
    applicationImage: `${IMG_BASE}/UK-BC001-B.jpg`,
  },
  {
    id: "pvc-uk-bc002",
    code: "UK-BC002",
    name: "Concrete Grey 1m Wide PVC Bathroom Shower Wall Panel",
    series: "UK Bathroom Cladding Series",
    seriesSlug: "uk-bathroom",
    size: "2400*1000*10mm",
    thickness: "10mm",
    color: "Concrete Grey",
    moq: 1000,
    unit: "sqm",
    unitPrice: 6,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "20 pcs/pallet",
    pcsPerCarton: 20,
    cartonSize: "2420*1020*150mm",
    netWeightPerCarton: "120kg",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "Concrete grey finish. 1m wide format for easy grid installation in shower enclosures.",
    image: `${IMG_BASE}/UK-BC002.jpg`,
  },
  {
    id: "pvc-uk-bc003",
    code: "UK-BC003",
    name: "Marble Effect PVC Interior Wall Cladding Easy Grid Panel",
    series: "UK Bathroom Cladding Series",
    seriesSlug: "uk-bathroom",
    size: "2400*1000*10mm",
    thickness: "10mm",
    color: "Marble White",
    moq: 1000,
    unit: "sqm",
    unitPrice: 6,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "20 pcs/pallet",
    pcsPerCarton: 20,
    cartonSize: "2420*1020*150mm",
    netWeightPerCarton: "120kg",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "Marble effect finish. Easy grid interlocking system for fast installation.",
    image: `${IMG_BASE}/UK-BC003.jpg`,
  },
  {
    id: "pvc-uk-bc004",
    code: "UK-BC004",
    name: "Granite PVC Ceiling Waterproof Wall Panel",
    series: "UK Bathroom Cladding Series",
    seriesSlug: "uk-bathroom",
    size: "2400*1000*10mm",
    thickness: "10mm",
    color: "Granite Grey",
    moq: 1000,
    unit: "sqm",
    unitPrice: 6,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "20 pcs/pallet",
    pcsPerCarton: 20,
    cartonSize: "2420*1020*150mm",
    netWeightPerCarton: "120kg",
    weightPerPiece: "6kg",
    leadTime: LEAD_TIME,
    remarks: "Granite grey finish. Fully waterproof for shower and wet room applications.",
    image: `${IMG_BASE}/UK-BC004.jpg`,
  },

  // ===== Standard Ceiling 25cm Series =====
  {
    id: "pvc-sc-2501",
    code: "SC-2501",
    name: "Techo Tablilla PVC Ceiling Panel",
    series: "Standard Ceiling 25cm Series",
    seriesSlug: "standard-ceiling",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Glossy White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Standard 25cm width, 5.95m length. Glossy white printing surface.",
    image: `${IMG_BASE}/SC-2501.jpg`,
  },
  {
    id: "pvc-sc-2502",
    code: "SC-2502",
    name: "Cielo Raso PVC 25cm Interior Decoration Ceiling Panel",
    series: "Standard Ceiling 25cm Series",
    seriesSlug: "standard-ceiling",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Glossy White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Cielo Raso (ceiling) panel for interior decoration. 25cm width standard format.",
    image: `${IMG_BASE}/SC-2502.jpg`,
  },
  {
    id: "pvc-sc-2503",
    code: "SC-2503",
    name: "Factory Direct Sale Interior Decorative PVC Ceiling Panel",
    series: "Standard Ceiling 25cm Series",
    seriesSlug: "standard-ceiling",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Decorative White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Factory direct sale decorative PVC panel for interior ceiling and wall application.",
    image: `${IMG_BASE}/SC-2503.jpg`,
    textureImage: `${IMG_BASE}/SC-2503-A.jpg`,
    applicationImage: `${IMG_BASE}/SC-2503-B.jpg`,
  },
  {
    id: "pvc-sc-2504",
    code: "SC-2504",
    name: "Interior Decorative PVC Panel for Ceiling and Wall",
    series: "Standard Ceiling 25cm Series",
    seriesSlug: "standard-ceiling",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Decorative White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Versatile decorative PVC panel suitable for both ceiling and wall interior applications.",
    image: `${IMG_BASE}/SC-2504.jpg`,
  },
  {
    id: "pvc-sc-2505",
    code: "SC-2505",
    name: "Techos En PVC Wall Panels Economy Grade",
    series: "Standard Ceiling 25cm Series",
    seriesSlug: "standard-ceiling",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Matte White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Economy grade Techos En PVC wall panel. Competitive pricing for bulk orders.",
    image: `${IMG_BASE}/SC-2505.jpg`,
  },

  // ===== Wide Ceiling 30cm Series =====
  {
    id: "pvc-wc-3001",
    code: "WC-3001",
    name: "Cielo Raso En PVC Blanco 30cm Plastic Ceiling Panel",
    series: "Wide Ceiling 30cm Series",
    seriesSlug: "wide-ceiling",
    size: "5950*300*8mm",
    thickness: "8mm",
    color: "Blanco White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.3,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*310*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Blanco (white) finish 30cm wide PVC ceiling panel. Fireproof and heat-insulating.",
    image: `${IMG_BASE}/WC-3001.jpg`,
  },
  {
    id: "pvc-wc-3002",
    code: "WC-3002",
    name: "Cielo Raso PVC Techo Para Decoracion De Casa",
    series: "Wide Ceiling 30cm Series",
    seriesSlug: "wide-ceiling",
    size: "5950*300*8mm",
    thickness: "8mm",
    color: "Decorative White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.3,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*310*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Cielo Raso PVC ceiling panel for home decoration (Techo Para Decoracion De Casa). 30cm width.",
    image: `${IMG_BASE}/WC-3002.jpg`,
  },
  {
    id: "pvc-wc-3003",
    code: "WC-3003",
    name: "250mm 300mm Wide PVC Ceiling Panels for Interior",
    series: "Wide Ceiling 30cm Series",
    seriesSlug: "wide-ceiling",
    size: "5950*300*8mm",
    thickness: "8mm",
    color: "Wood Grain Multi-Color",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*310*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Multi-color wood grain display. Available in 250mm and 300mm widths for interior ceiling decoration.",
    image: `${IMG_BASE}/WC-3003.jpg`,
  },

  // ===== Glossy Printing Series =====
  {
    id: "pvc-gp-6001",
    code: "GP-6001",
    name: "Glossy Printing 25cm Plastic Ceiling Tiles PVC",
    series: "Glossy Printing Series",
    seriesSlug: "glossy-printing",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Glossy Printing",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Glossy printing surface. 25cm width standard ceiling tile format.",
    image: `${IMG_BASE}/GP-6001.jpg`,
  },
  {
    id: "pvc-gp-6002",
    code: "GP-6002",
    name: "High Glossy 25cm Ceiling Tiles Interior PVC Panel",
    series: "Glossy Printing Series",
    seriesSlug: "glossy-printing",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "High Gloss",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "High glossy surface finish. 25cm width ceiling tile for interior decoration.",
    image: `${IMG_BASE}/GP-6002.jpg`,
  },
  {
    id: "pvc-gp-6003",
    code: "GP-6003",
    name: "600*600*7mm Interior Ceiling Design PVC Panel",
    series: "Glossy Printing Series",
    seriesSlug: "glossy-printing",
    size: "600*600*7mm",
    thickness: "7mm",
    color: "Ceiling Design Pattern",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.5,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "620*620*150mm",
    netWeightPerCarton: "20kg",
    weightPerPiece: "0.5kg",
    leadTime: LEAD_TIME,
    remarks: "600*600mm ceiling tile format with interior design pattern surface.",
    image: `${IMG_BASE}/GP-6003.jpg`,
  },
  {
    id: "pvc-gp-6004",
    code: "GP-6004",
    name: "PVC Ceiling Panels Ceiling Design PVC Panel",
    series: "Glossy Printing Series",
    seriesSlug: "glossy-printing",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Ceiling Design White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.25,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Ceiling design pattern surface. Versatile PVC panel for ceiling decoration.",
    image: `${IMG_BASE}/GP-6004.jpg`,
  },

  // ===== Laminated Wood Grain Series =====
  {
    id: "pvc-lw-001",
    code: "LW-001",
    name: "Laminated Wooden Color PVC Ceiling Panel",
    series: "Laminated Wood Grain Series",
    seriesSlug: "laminated-wood",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Wood Color",
    moq: 1500,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Wood color laminated surface with hot stamping technology.",
    image: `${IMG_BASE}/LW-001.jpg`,
  },
  {
    id: "pvc-lw-002",
    code: "LW-002",
    name: "Laminated Wood Design Lebanon Paneling PVC Ceiling",
    series: "Laminated Wood Grain Series",
    seriesSlug: "laminated-wood",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Lebanon Wood",
    moq: 500,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Lebanon wood design. Lower MOQ of 500 sqm for project flexibility.",
    image: `${IMG_BASE}/LW-002.jpg`,
    textureImage: `${IMG_BASE}/LW-002-A.jpg`,
    applicationImage: `${IMG_BASE}/LW-002-B.jpg`,
  },
  {
    id: "pvc-lw-003",
    code: "LW-003",
    name: "Wood Design Muros Wall Decoration Interior PVC Panel",
    series: "Laminated Wood Grain Series",
    seriesSlug: "laminated-wood",
    size: "5950*250*7mm",
    thickness: "7mm",
    color: "Wood Design",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.45,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Wood design muros wall panel for interior decoration. Laminated surface finish.",
    image: `${IMG_BASE}/LW-003.jpg`,
  },
  {
    id: "pvc-lw-004",
    code: "LW-004",
    name: "Techos En PVC Interior Laminated PVC Ceiling Panel",
    series: "Laminated Wood Grain Series",
    seriesSlug: "laminated-wood",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Laminated Wood",
    moq: 500,
    unit: "sqm",
    unitPrice: 1.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Interior laminated PVC ceiling panel (Techos En PVC). Wood grain laminated surface finish.",
    image: `${IMG_BASE}/LW-004.jpg`,
  },

  // ===== Tongue & Groove Series =====
  {
    id: "pvc-tg-001",
    code: "TG-001",
    name: "Flat and Groove New Mold Techos PVC Wall Panel",
    series: "Tongue & Groove Series",
    seriesSlug: "tongue-groove",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Flat Groove White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.3,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Flat and groove new mold design. Tongue and groove interlocking for seamless installation.",
    image: `${IMG_BASE}/TG-001.jpg`,
  },
  {
    id: "pvc-tg-002",
    code: "TG-002",
    name: "SONSILL Faux Plafond PVC Tongue and Groove Ceiling",
    series: "Tongue & Groove Series",
    seriesSlug: "tongue-groove",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "V-Groove White",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.3,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "SONSILL brand faux plafond panel. V-groove tongue and groove interlocking system.",
    image: `${IMG_BASE}/TG-002.jpg`,
  },
  {
    id: "pvc-tg-003",
    code: "TG-003",
    name: "New High Glossy Tongue and Groove PVC Ceiling Panel",
    series: "Tongue & Groove Series",
    seriesSlug: "tongue-groove",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Glossy T&G",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.4,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "New high glossy tongue and groove panel. 250mm width interlocking ceiling system.",
    image: `${IMG_BASE}/TG-003.jpg`,
    textureImage: `${IMG_BASE}/TG-003-A.jpg`,
    applicationImage: `${IMG_BASE}/TG-003-B.jpg`,
  },
  {
    id: "pvc-tg-004",
    code: "TG-004",
    name: "250x7.5mm Forro PVC Wall Panel Lamination V-Groove",
    series: "Tongue & Groove Series",
    seriesSlug: "tongue-groove",
    size: "5950*250*7.5mm",
    thickness: "7.5mm",
    color: "V-Groove Wood",
    moq: 1000,
    unit: "sqm",
    unitPrice: 2.8,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Forro PVC wall panel with wood lamination. 7.5mm thickness V-groove premium grade.",
    image: `${IMG_BASE}/TG-004.jpg`,
  },

  // ===== Self-Adhesive Series =====
  {
    id: "pvc-sa-001",
    code: "SA-001",
    name: "Modern Self-Adhesive PVC Geometric Pattern Panel",
    series: "Self-Adhesive Series",
    seriesSlug: "self-adhesive",
    size: "580*580mm",
    thickness: "3mm",
    color: "Geometric Pattern",
    moq: 500,
    unit: "pc",
    unitPrice: 1.2,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "50 pcs/ctn",
    pcsPerCarton: 50,
    cartonSize: "600*600*200mm",
    netWeightPerCarton: "20kg",
    weightPerPiece: "0.4kg",
    leadTime: LEAD_TIME,
    remarks: "Peel & stick self-adhesive. 3D geometric pattern for DIY wall decor.",
    image: `${IMG_BASE}/SA-001.jpg`,
  },
  {
    id: "pvc-sa-002",
    code: "SA-002",
    name: "580*580mm Self-Adhesive PVC Waterproof Wall Decor",
    series: "Self-Adhesive Series",
    seriesSlug: "self-adhesive",
    size: "580*580mm",
    thickness: "3mm",
    color: "Metal Grille",
    moq: 500,
    unit: "pc",
    unitPrice: 0.98,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "50 pcs/ctn",
    pcsPerCarton: 50,
    cartonSize: "600*600*200mm",
    netWeightPerCarton: "20kg",
    weightPerPiece: "0.4kg",
    leadTime: LEAD_TIME,
    remarks: "Metal grille pattern. Waterproof self-adhesive backing for easy application.",
    image: `${IMG_BASE}/SA-002.jpg`,
  },
  {
    id: "pvc-sa-003",
    code: "SA-003",
    name: "3D Self-Adhesive Waterproof Fireproof Wall Panel",
    series: "Self-Adhesive Series",
    seriesSlug: "self-adhesive",
    size: "580*580mm",
    thickness: "5mm",
    color: "3D Striped",
    moq: 1000,
    unit: "sqm",
    unitPrice: 2.1,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "50 pcs/ctn",
    pcsPerCarton: 50,
    cartonSize: "600*600*300mm",
    netWeightPerCarton: "30kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "5mm thickness 3D striped panel. Waterproof and fireproof. Priced per sqm.",
    image: `${IMG_BASE}/SA-003.jpg`,
    textureImage: `${IMG_BASE}/SA-003-A.jpg`,
    applicationImage: `${IMG_BASE}/SA-003-B.jpg`,
  },

  // ===== Hot Stamping Series =====
  {
    id: "pvc-hs-001",
    code: "HS-001",
    name: "Factory Price Decorative Hot Stamping PVC Panel",
    series: "Hot Stamping Series",
    seriesSlug: "hot-stamping",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Hot Stamping Gold",
    moq: 500,
    unit: "sqm",
    unitPrice: 1.3,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Gold metallic hot stamping finish. Decorative ceiling and wall panel.",
    image: `${IMG_BASE}/HS-001.jpg`,
  },
  {
    id: "pvc-hs-002",
    code: "HS-002",
    name: "25*8mm Best Price Hot Stamping PVC Ceiling Panel",
    series: "Hot Stamping Series",
    seriesSlug: "hot-stamping",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Hot Stamping Silver",
    moq: 3000,
    unit: "sqm",
    unitPrice: 1.0,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Silver metallic hot stamping finish. Best value pricing for bulk orders.",
    image: `${IMG_BASE}/HS-002.jpg`,
  },
  {
    id: "pvc-hs-003",
    code: "HS-003",
    name: "PVC Panels Ceiling Design Lamination Surface Panel",
    series: "Hot Stamping Series",
    seriesSlug: "hot-stamping",
    size: "5950*250*8mm",
    thickness: "8mm",
    color: "Lamination Surface",
    moq: 1000,
    unit: "sqm",
    unitPrice: 1.76,
    currency: CURRENCY,
    incoterm: INCOTERM,
    packaging: "40 pcs/ctn",
    pcsPerCarton: 40,
    cartonSize: "5960*260*120mm",
    netWeightPerCarton: "25kg",
    weightPerPiece: "0.6kg",
    leadTime: LEAD_TIME,
    remarks: "Lamination surface with hot stamping. Premium ceiling design panel.",
    image: `${IMG_BASE}/HS-003.jpg`,
  },
];

// FAQ 数据 — PVC天花板/墙板常见问题
export const pvcPanelFAQs = [
  {
    question: "Are PVC ceiling and wall panels waterproof?",
    answer:
      "Yes. PVC panels are fully waterproof and moisture-resistant, making them ideal for bathrooms, kitchens, shower enclosures, and wet rooms. Unlike gypsum or mineral fiber ceiling tiles, PVC panels will not absorb water, warp, or develop mold in humid environments.",
  },
  {
    question: "What is the fire rating of PVC panels?",
    answer:
      "Our PVC ceiling panels are manufactured with fireproof and heat-insulating properties. They meet international fire safety standards for interior building materials. Specific fire rating certificates (such as B1 or equivalent) are available upon request. Please contact our sales team for the certificate applicable to your selected model.",
  },
  {
    question: "How are PVC ceiling panels installed?",
    answer:
      "PVC panels use a tongue and groove interlocking system for seamless installation. They can be installed over existing ceilings or wooden battens using staples, screws, or adhesive. Self-adhesive series panels feature peel-and-stick backing for DIY installation. No specialized tools are required. Installation guides are available upon request.",
  },
  {
    question: "What is the expected lifespan of PVC panels?",
    answer:
      "PVC ceiling and wall panels are highly durable with an expected lifespan of 15-20 years under normal indoor conditions. They are resistant to fading, cracking, and moisture damage. The color and surface finish remain stable over time when used in interior applications away from direct UV exposure.",
  },
  {
    question: "What is the MOQ (Minimum Order Quantity) for PVC panels?",
    answer:
      "MOQ varies by product series. Standard ceiling panels typically have an MOQ of 3,000 sqm. UK bathroom cladding panels have an MOQ of 1,000 sqm. Self-adhesive panels are available from 500 pcs. Some specialized models offer lower MOQs of 500-1,000 sqm. Please check each product detail page or contact our sales team for exact MOQ.",
  },
  {
    question: "What are the shipping and packaging details?",
    answer:
      "Standard 5.95m ceiling panels are packed 40 pcs per carton (5960*260*120mm, ~25kg). UK bathroom panels are packed 20 pcs per pallet (2420*1020*150mm, ~120kg). Self-adhesive panels are packed 50 pcs per carton. FOB pricing is quoted in USD. 20GP and 40HQ container loading quantities are available upon request. Please contact our sales team for freight quotations to your destination port.",
  },
  {
    question: "Can PVC panels be customized in terms of color, size, and pattern?",
    answer:
      "Yes. We offer customization for color, surface pattern (printing, lamination, hot stamping), and dimensions. Custom wood grain, marble effect, and metallic finishes are available. Minimum order quantities apply for custom designs. Please contact our sales team with your specific requirements for a detailed quotation.",
  },
  {
    question: "What certifications do your PVC panels carry?",
    answer:
      "Our PVC panels comply with international quality and safety standards including ISO, CE, and fire safety certifications (B1 fire rating). Products are tested for formaldehyde emissions, heavy metals, and flame retardancy. Specific certificates are available per product series. Please contact our sales team to request the relevant certificates for your market.",
  },
];

// 联系信息配置变量
export const PVC_PANEL_CONTACT = {
  email: "cindy@onestopbuildly.com",
  phone: "+86-13511316133",
  whatsapp: "+86-13511316133",
  company: "Haining Onestopbuildly Building Materials Co., Ltd.",
  address: "Room 108, Building 2, Fenghuang Commercial Building, Dingqiao Town, Haining, Zhejiang, China",
  factoryAddress: "No. 1, Shiquan Industrial Park, Tongyuan Town, Haiyan County, Jiaxing, Zhejiang",
};

// 工具函数
export function formatPrice(product: PVCPanelProduct): string {
  if (product.unitPrice === null || product.unitPrice === undefined) {
    return "Price available on request";
  }
  return `${product.currency} ${product.unitPrice} / ${product.unit}`;
}

export function formatPriceShort(product: PVCPanelProduct): string {
  if (product.unitPrice === null || product.unitPrice === undefined) {
    return "Request a Quote";
  }
  return `${product.currency} ${product.unitPrice}/${product.unit}`;
}

export function getProductsBySeries(seriesSlug: string): PVCPanelProduct[] {
  return pvcPanelProducts.filter((p) => p.seriesSlug === seriesSlug);
}

export function getUniqueSizes(): string[] {
  return [...new Set(pvcPanelProducts.map((p) => p.size))].sort();
}

export function getUniqueSeries(): PVCPanelSeries[] {
  return pvcPanelSeries;
}

export function getUniqueColors(): string[] {
  return [...new Set(pvcPanelProducts.map((p) => p.color))].sort();
}

export function getUniqueCodes(): string[] {
  return [...new Set(pvcPanelProducts.map((p) => p.code))].sort();
}
